In [1]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(x)
n_components=2
x_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print(x)
print("\n Reconstructed matrix(with reduced dimensions):")
print(x_reconstructed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Reconstructed matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
